---
- hosts: all
  remote_user: root
  vars_files:
    - monitors.yml

  tasks:
    - name: install stuff
      apt: name={{item}} state=present update_cache=yes
      with_items:
        - snmpd

    - name: copy config
      template:
        src=templates/snmpd.debian.conf.j2
        dest=/etc/snmp/snmpd.conf
        owner=root
        group=root
        mode=0600

    - name: enable and start service
      service: name=snmpd state=restarted enabled=yes

    - name: open firewall
      ufw: rule=allow proto=udp insert=1 src={{item}} port=161
      with_items: "{{ snmpd.monitors }}"

