---
- hosts: all
  remote_user: root

  tasks:
    - name: install stuff
      apt: name={{item}} state=present update_cache=yes
      with_items:
        - snmpd
    - name: copy config
      copy: src=files/snmpd.debian.conf dest=/etc/snmp/snmpd.conf

    - name: enable and start service
      service: name=snmpd state=started enabled=yes

    - name: open firewall
      ufw: rule=allow proto=udp insert=1 src=128.193.14.4 port=161

    - name: open firewall again
      ufw: rule=allow proto=udp insert=1 src=128.193.15.24 port=161
